// Luminous Arcana - SKSE plugin
// Copyright (C) 2026 izzydoingit
// GPL-3.0-or-later; see LICENSE.txt and the notice at the top of main.cpp.
//
// Pass 0: the settings Luminous Arcana's lights were made against, written onto the game's own magic lights.

#include "Plugin.h"

namespace Plugin
{
	// ------------------------------------------------------------------ pass 0: the light settings
	// Luminous Arcana has no plugin of its own. The magic lights below carry the settings its lights
	// were made against - radius, color, flags (inverse square among them), falloff, size, near
	// distance, flicker and fade - and this pass writes them onto the game's own light records when
	// the game has loaded, before anything copies a light. A record whose winning version comes from
	// CS Light.esp already carries these exact values and is left as it is; every other record gets
	// them, whichever plugin changed it last. Generated by lagen.py laplugin.
	struct LightSetting
	{
		const char*   file;
		std::uint32_t localID;
		const char*   editorID;
		std::uint32_t radius;
		int           r, g, b;
		std::uint32_t flags;
		float         falloff, fov, nearDistance, flickerIntensity, flickerMovement, fade;
	};

	const LightSetting kLightSettings[] = {
		{ "Skyrim.esm", 0x0140EC, "MagicLightFireInHand", 36, 228, 125, 60, 0x4041, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.45f },
		{ "Skyrim.esm", 0x01CBB3, "MagicLightFireball01", 300, 185, 110, 50, 0x4041, 1.0f, 2.0f, 0.0f, 0.5f, 1.8f, 1.8f },
		{ "Skyrim.esm", 0x02016B, "MagicLightTelekinesisHand01", 25, 120, 83, 58, 0x4000, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.15f },
		{ "Skyrim.esm", 0x028530, "MagicLightInvisHand01", 25, 73, 73, 154, 0x4000, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.15f },
		{ "Skyrim.esm", 0x03BA90, "MagicLightSummon01", 32, 68, 68, 144, 0x4001, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.225f },
		{ "Skyrim.esm", 0x03F1B5, "MagicLightHealHand01", 50, 200, 173, 136, 0x4000, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.3f },
		{ "Skyrim.esm", 0x041F09, "MagicLightLightSpellHand01", 32, 143, 190, 220, 0x4001, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.2f },
		{ "Skyrim.esm", 0x04C6DB, "MagicLightTurnUndead01", 190, 156, 159, 188, 0x4040, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.225f },
		{ "Skyrim.esm", 0x04C6DC, "MagicLightTurnUndeadHand01", 45, 120, 126, 169, 0x4040, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.225f },
		{ "Skyrim.esm", 0x056ACA, "MagicLightShockProjectile01", 360, 117, 117, 190, 0x4009, 1.0f, 2.0f, 1.0f, 0.0f, 0.0f, 2.25f },
		{ "Skyrim.esm", 0x057C68, "MagicLightShockHand", 30, 92, 92, 176, 0x4009, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.255f },
		{ "Skyrim.esm", 0x06B110, "MagicLightNightEyeHand01", 32, 111, 131, 186, 0x4001, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.225f },
		{ "Skyrim.esm", 0x06EBCC, "MagicLightParalyzeHand", 45, 127, 190, 117, 0x4000, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.15f },
		{ "Skyrim.esm", 0x07331B, "MagicLightIllusionPosHand01", 40, 122, 192, 185, 0x4000, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.1875f },
		{ "Skyrim.esm", 0x07331E, "MagicLightIllusionPosProjectile01", 200, 79, 163, 138, 0x4000, 1.0f, 2.0f, 1.0f, 0.0f, 0.0f, 1.5f },
		{ "Skyrim.esm", 0x07479A, "MagicLightIllusionNegHand01", 30, 178, 103, 97, 0x4000, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.3f },
		{ "Skyrim.esm", 0x07479B, "MagicLightIllusionNegProjectile01", 200, 164, 78, 78, 0x4000, 1.0f, 2.0f, 1.0f, 0.0f, 0.0f, 1.5f },
		{ "Skyrim.esm", 0x075347, "MagicLightReanimateHand", 32, 55, 56, 119, 0x4001, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.165f },
		{ "Skyrim.esm", 0x0D13E7, "MagicLightReanimate1", 300, 11, 75, 196, 0x4001, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.15f },
		{ "Skyrim.esm", 0x10FBEC, "MagicLightFireball02", 400, 225, 156, 99, 0x4001, 1.0f, 2.0f, 1.0f, 0.0f, 0.0f, 1.5f },
	};

	constexpr std::string_view kSameValuesPlugin = "CS Light.esp";

	void LightSettings()
	{
		auto*       dh = RE::TESDataHandler::GetSingleton();
		std::size_t set = 0, missing = 0, renamed = 0, failed = 0, replaced = 0, same = 0;
		for (const auto& s : kLightSettings) {
			auto* light = dh->LookupForm<RE::TESObjectLIGH>(s.localID, s.file);
			if (!light) {
				++missing;
				SKSE::log::warn("[LIGHT-MISSING] {} {:06X} ({}) is not in this load order", s.file, s.localID, s.editorID);
				continue;
			}
			const auto id = EditorID(light);
			if (!id.empty() && Lower(id) != Lower(s.editorID)) {
				++renamed;
				SKSE::log::warn("[LIGHT-RENAMED] {} {:06X} is {} here, expected {}; left alone", s.file, s.localID, id, s.editorID);
				continue;
			}
			// what the load order gave this light, and which plugin gave it - written to the log so a
			// look that differs from the configs can be traced to the record the game actually loaded
			const auto*       owner = light->GetDescriptionOwnerFile();
			const std::string ownerName = owner ? std::string(owner->GetFilename()) : std::string("(unknown)");
			const auto        was = std::format("radius {} | color {},{},{} | flags {:X} | size {} | fade {}", light->data.radius,
				   light->data.color.red, light->data.color.green, light->data.color.blue, light->data.flags.underlying(), light->data.fov,
				   light->fade);
			if (Lower(ownerName) == Lower(kSameValuesPlugin)) {
				++same;
				SKSE::log::info("[LIGHT-KEPT] {} | {} already sets these values", Label(light), ownerName);
				continue;
			}
			if (Lower(ownerName) != Lower(s.file)) {
				++replaced;
				SKSE::log::warn("[LIGHT-REPLACED] {} | {} last changed it ({}); Luminous Arcana's values go over it", Label(light),
					ownerName, was);
			}
			light->data.radius = s.radius;
			light->data.color.red = static_cast<std::uint8_t>(s.r);
			light->data.color.green = static_cast<std::uint8_t>(s.g);
			light->data.color.blue = static_cast<std::uint8_t>(s.b);
			light->data.flags = static_cast<RE::TES_LIGHT_FLAGS>(s.flags);
			light->data.fallofExponent = s.falloff;
			light->data.fov = s.fov;
			light->data.nearDistance = s.nearDistance;
			light->data.flickerIntensityAmplitude = s.flickerIntensity;
			light->data.flickerMovementAmplitude = s.flickerMovement;
			light->fade = s.fade;
			// read back what the game now holds
			if (light->data.radius != s.radius || light->data.flags.underlying() != s.flags || light->fade != s.fade ||
				light->data.fov != s.fov || light->data.color.red != static_cast<std::uint8_t>(s.r)) {
				++failed;
				SKSE::log::warn("[LIGHT-FAILED] {} | the values did not take", Label(light));
				continue;
			}
			++set;
			SKSE::log::info("[LIGHT-SET] {} | radius {} | color {},{},{} | flags {:X} | fade {} | was {}", Label(light), s.radius, s.r,
				s.g, s.b, s.flags, s.fade, was);
		}
		SKSE::log::info("light settings: {} of {} set ({} over another plugin's values), {} already set by {}, {} not in this load "
						"order, {} renamed and left alone, {} failed",
			set, std::size(kLightSettings), replaced, same, kSameValuesPlugin, missing, renamed, failed);
	}
}
