// Luminous Arcana - SKSE plugin
// Copyright (C) 2026 izzydoingit
// GPL-3.0-or-later; see LICENSE.txt and the notice at the top of main.cpp.
//
// Pass 0: Luminous Arcana's own copies of the game's magic lights, carrying the look its lights were made with.

#include "Plugin.h"

namespace Plugin
{
	// ------------------------------------------------------------------ pass 0: Luminous Arcana's own magic lights
	// Every magic effect, projectile, explosion and hazard that uses one of the game's magic lights below
	// is pointed at Luminous Arcana's OWN copy of that light, made here, carrying the look its lights were
	// made with - radius, color, flags (inverse square among them), falloff, size, near distance, flicker
	// and fade. The game's light records keep their own color, size and fade: the Light Placer configs
	// state those themselves. Two things a Light Placer config cannot state are set on the record Light
	// Placer reads - the dynamic flag and the flicker strength. Generated by lagen.py laplugin.
	struct LightSetting
	{
		const char*   file;
		std::uint32_t localID;
		const char*   editorID;
		std::uint32_t radius;
		int           r, g, b;
		std::uint32_t flags;
		float         falloff, fov, nearDistance, flickerIntensity, flickerMovement, fade;
	};

	const LightSetting kLightSettings[] = {
		{ "Skyrim.esm", 0x0140EC, "MagicLightFireInHand", 36, 228, 125, 60, 0x4041, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.45f },
		{ "Skyrim.esm", 0x01CBB3, "MagicLightFireball01", 300, 185, 110, 50, 0x4041, 1.0f, 2.0f, 0.0f, 0.5f, 1.8f, 1.8f },
		{ "Skyrim.esm", 0x02016B, "MagicLightTelekinesisHand01", 25, 120, 83, 58, 0x4000, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.15f },
		{ "Skyrim.esm", 0x028530, "MagicLightInvisHand01", 25, 73, 73, 154, 0x4000, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.15f },
		{ "Skyrim.esm", 0x03BA90, "MagicLightSummon01", 32, 68, 68, 144, 0x4001, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.225f },
		{ "Skyrim.esm", 0x03F1B5, "MagicLightHealHand01", 50, 200, 173, 136, 0x4000, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.3f },
		{ "Skyrim.esm", 0x041F09, "MagicLightLightSpellHand01", 32, 143, 190, 220, 0x4001, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.2f },
		{ "Skyrim.esm", 0x04C6DB, "MagicLightTurnUndead01", 190, 156, 159, 188, 0x4040, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.225f },
		{ "Skyrim.esm", 0x04C6DC, "MagicLightTurnUndeadHand01", 45, 120, 126, 169, 0x4040, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.225f },
		{ "Skyrim.esm", 0x056ACA, "MagicLightShockProjectile01", 360, 117, 117, 190, 0x4009, 1.0f, 2.0f, 1.0f, 0.0f, 0.0f, 2.25f },
		{ "Skyrim.esm", 0x057C68, "MagicLightShockHand", 30, 92, 92, 176, 0x4009, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.255f },
		{ "Skyrim.esm", 0x06B110, "MagicLightNightEyeHand01", 32, 111, 131, 186, 0x4001, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.225f },
		{ "Skyrim.esm", 0x06EBCC, "MagicLightParalyzeHand", 45, 127, 190, 117, 0x4000, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.15f },
		{ "Skyrim.esm", 0x07331B, "MagicLightIllusionPosHand01", 40, 122, 192, 185, 0x4000, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.1875f },
		{ "Skyrim.esm", 0x07331E, "MagicLightIllusionPosProjectile01", 200, 79, 163, 138, 0x4000, 1.0f, 2.0f, 1.0f, 0.0f, 0.0f, 1.5f },
		{ "Skyrim.esm", 0x07479A, "MagicLightIllusionNegHand01", 30, 178, 103, 97, 0x4000, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.3f },
		{ "Skyrim.esm", 0x07479B, "MagicLightIllusionNegProjectile01", 200, 164, 78, 78, 0x4000, 1.0f, 2.0f, 1.0f, 0.0f, 0.0f, 1.5f },
		{ "Skyrim.esm", 0x075347, "MagicLightReanimateHand", 32, 55, 56, 119, 0x4001, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.165f },
		{ "Skyrim.esm", 0x0D13E7, "MagicLightReanimate1", 300, 11, 75, 196, 0x4001, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.15f },
		{ "Skyrim.esm", 0x10FBEC, "MagicLightFireball02", 400, 225, 156, 99, 0x4001, 1.0f, 2.0f, 1.0f, 0.0f, 0.0f, 1.5f },
	};

	void LightSettings()
	{
		auto*       dh = RE::TESDataHandler::GetSingleton();
		std::unordered_map<const RE::TESObjectLIGH*, RE::TESObjectLIGH*> ours;
		std::size_t made = 0, missing = 0, renamed = 0, failed = 0;
		for (const auto& s : kLightSettings) {
			auto* light = dh->LookupForm<RE::TESObjectLIGH>(s.localID, s.file);
			if (!light) {
				++missing;
				SKSE::log::warn("[LIGHT-MISSING] {} {:06X} ({}) is not in this load order", s.file, s.localID, s.editorID);
				continue;
			}
			const auto id = EditorID(light);
			if (!id.empty() && Lower(id) != Lower(s.editorID)) {
				++renamed;
				SKSE::log::warn("[LIGHT-RENAMED] {} {:06X} is {} here, expected {}; left alone", s.file, s.localID, id, s.editorID);
				continue;
			}
			auto* copy = CopyLight(light);
			if (!copy) {
				++failed;
				SKSE::log::warn("[LIGHT-FAILED] {} | could not make a copy", Label(light));
				continue;
			}
			copy->data.radius = s.radius;
			copy->data.color.red = static_cast<std::uint8_t>(s.r);
			copy->data.color.green = static_cast<std::uint8_t>(s.g);
			copy->data.color.blue = static_cast<std::uint8_t>(s.b);
			copy->data.flags = static_cast<RE::TES_LIGHT_FLAGS>(s.flags);
			copy->data.fallofExponent = s.falloff;
			copy->data.fov = s.fov;
			copy->data.nearDistance = s.nearDistance;
			copy->data.flickerIntensityAmplitude = s.flickerIntensity;
			copy->data.flickerMovementAmplitude = s.flickerMovement;
			copy->fade = s.fade;
			// read back what the copy now holds
			if (copy->data.radius != s.radius || copy->data.flags.underlying() != s.flags || copy->fade != s.fade ||
				copy->data.fov != s.fov || copy->data.color.red != static_cast<std::uint8_t>(s.r)) {
				++failed;
				SKSE::log::warn("[LIGHT-FAILED] {} | the copy's values did not take", Label(light));
				continue;
			}
			// what Light Placer reads off the record and a config cannot state
			const auto dynamic = static_cast<std::uint32_t>(RE::TES_LIGHT_FLAGS::kDynamic);
			if ((s.flags & dynamic) && !(light->data.flags.underlying() & dynamic)) {
				light->data.flags = static_cast<RE::TES_LIGHT_FLAGS>(light->data.flags.underlying() | dynamic);
			}
			light->data.flickerIntensityAmplitude = s.flickerIntensity;
			light->data.flickerMovementAmplitude = s.flickerMovement;
			RememberEditorID(copy, (std::string(s.editorID) + " (Luminous Arcana)").c_str());
			ours[light] = copy;
			++made;
			SKSE::log::info("[LIGHT-OURS] {} | radius {} | color {},{},{} | flags {:X} | size {} | fade {}", Label(light), s.radius,
				s.r, s.g, s.b, s.flags, s.fov, s.fade);
		}
		std::size_t pointed = 0;
		const auto point = [&](RE::TESObjectLIGH*& a_slot) {
			if (a_slot) {
				if (const auto it = ours.find(a_slot); it != ours.end()) {
					a_slot = it->second;
					++pointed;
				}
			}
		};
		for (auto* f : dh->GetFormArray<RE::EffectSetting>()) {
			if (f) point(f->data.light);
		}
		for (auto* f : dh->GetFormArray<RE::BGSProjectile>()) {
			if (f) {
				point(f->data.light);
				point(f->data.muzzleFlashLight);
			}
		}
		for (auto* f : dh->GetFormArray<RE::BGSExplosion>()) {
			if (f) point(f->data.light);
		}
		for (auto* f : dh->GetFormArray<RE::BGSHazard>()) {
			if (f) point(f->data.light);
		}
		SKSE::log::info("light settings: {} of {} lights of our own made, {} uses pointed at them, {} not in this load order, "
						"{} renamed and left alone, {} failed",
			made, std::size(kLightSettings), pointed, missing, renamed, failed);
	}
}
